Read files from config directory
Instead of hard-coding the keys and files, use a directory under
~/.config/practice-musicid/ (defaulting to the default/ subdirectory)
and read files from there; the file names act as keys. Usually, you’d
create these as symlinks to somewhere else, but it should also work if
you directly copy files there, I guess. (The default/ subdirectory can
also be a symlink to another named subdirectory, letting you easily
change what the default points to at your leisure.)

diff --git a/practice-musicid b/practice-musicid
--- a/practice-musicid
+++ b/practice-musicid
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+gamebasedir=${XDG_CONFIG_HOME:-~/.config}/practice-musicid/
+
 max_duration=30
 if ! tmp=$(getopt -o 't:h' --long 'duration:,help' -n "$0" -- "$@"); then
     exit 1
@@ -23,9 +25,11 @@ while true; do
             continue
             ;;
         '-h'|'--help')
-            printf 'Usage: %s [-t|--duration DURATION]\n' "$0"
-            printf 'The game will repeatedly play a random snippet (up to DURATION)\n'
-            printf 'of a random music file and ask you to identify the file.\n'
+            printf 'Usage: %s [-t|--duration DURATION] [DIRECTORY]\n' "$0"
+            printf 'The game will repeatedly play a random snippet (up to DURATION, default 30s)\n'
+            printf 'of a random music file in DIRECTORY (default "default"),\n'
+            printf 'which should be a subdirectory of %s,\n' "$gamebasedir"
+            printf 'and ask you to identify the file.\n'
             printf 'Exit with Ctrl-C.\n'
             exit 0
             ;;
@@ -36,25 +40,26 @@ while true; do
     esac
 done
 
-# declare files and their short keys (which the user will later enter)
-declare -A files=(
-    [rach2-1]='/home/lucas/Music/Sergei Rachmaninoff, Pyotr Ilyich Tchaikovsky; Sviatoslav Richter, Stanisław Wisłocki, Herbert von Karajan/Rachmaninov: Piano Concerto no. 2 - Tchaikovsky: Piano Concerto no. 1/Disc 1 - 01 - Piano Concerto no. 2 in C minor, op. 18: I. Moderato.flac'
-    [rach2-2]='/home/lucas/Music/Sergei Rachmaninoff, Pyotr Ilyich Tchaikovsky; Sviatoslav Richter, Stanisław Wisłocki, Herbert von Karajan/Rachmaninov: Piano Concerto no. 2 - Tchaikovsky: Piano Concerto no. 1/Disc 1 - 02 - Piano Concerto no. 2 in C minor, op. 18: II. Adagio sostenuto.flac'
-    [rach2-3]='/home/lucas/Music/Sergei Rachmaninoff, Pyotr Ilyich Tchaikovsky; Sviatoslav Richter, Stanisław Wisłocki, Herbert von Karajan/Rachmaninov: Piano Concerto no. 2 - Tchaikovsky: Piano Concerto no. 1/Disc 1 - 03 - Piano Concerto no. 2 in C minor, op. 18: III. Allegro scherzando.flac'
-    [tchaik1-1]='/home/lucas/Music/Sergei Rachmaninoff, Pyotr Ilyich Tchaikovsky; Sviatoslav Richter, Stanisław Wisłocki, Herbert von Karajan/Rachmaninov: Piano Concerto no. 2 - Tchaikovsky: Piano Concerto no. 1/Disc 1 - 04 - Piano Concerto no. 1 in B-flat minor, op. 23: I. Allegro non troppo e molto maestoso – Allegro con spirito.flac'
-    [tchaik1-2]='/home/lucas/Music/Sergei Rachmaninoff, Pyotr Ilyich Tchaikovsky; Sviatoslav Richter, Stanisław Wisłocki, Herbert von Karajan/Rachmaninov: Piano Concerto no. 2 - Tchaikovsky: Piano Concerto no. 1/Disc 1 - 05 - Piano Concerto no. 1 in B-flat minor, op. 23: II. Andantino semplice – Prestissimo – Tempo I.flac'
-    [tchaik1-3]='/home/lucas/Music/Sergei Rachmaninoff, Pyotr Ilyich Tchaikovsky; Sviatoslav Richter, Stanisław Wisłocki, Herbert von Karajan/Rachmaninov: Piano Concerto no. 2 - Tchaikovsky: Piano Concerto no. 1/Disc 1 - 06 - Piano Concerto no. 1 in B-flat minor, op. 23: III. Allegro con fuoco.flac'
-)
-keys=("${!files[@]}")
+gamedir=$gamebasedir/${1:-default}
+if ! cd -- "$gamedir"; then
+    printf >&2 '%s: should be a directory with (symlinks to) audio files: %s\n' "$0" "$gamedir"
+    exit 1
+fi
+
+shopt -s nullglob
+files=(*)
+if ((${#files[@]} == 0)); then
+    printf >&2 '%s: directory is empty: %s\n' "$0" "$gamedir"
+    exit 1
+fi
 
 while true; do
     # pick a random file
-    key=${keys[RANDOM%${#keys[@]}]}
-    file=${files["$key"]}
+    file=${files[RANDOM%${#files[@]}]}
     # get its duration
     duration=$(LC_ALL=C ffprobe -i "$file" -show_entries format=duration -v quiet -of csv=p=0) # https://stackoverflow.com/a/22243834/1420237
     if [[ ! $duration ]]; then
-        printf 'Invalid duration for key %s (file %s)! Does the file exist?\n' "$key" "$file"
+        printf 'Invalid duration for file %s! Does the file exist?\n' "$file"
         continue
     fi
     # pick a random offset in the file
@@ -64,7 +69,7 @@ while true; do
     ffplay -ss "${offset}s" -t "${max_duration}s" -autoexit -nodisp -loglevel quiet -i "$file" > /dev/null &
 
     printf 'Which of these is it?\n'
-    printf '• %s\n' "${keys[@]}"
+    printf '• %s\n' "${files[@]}"
     printf '\n'
 
     IFS= read -r -p'> ' reply
@@ -72,9 +77,9 @@ while true; do
     kill %%
     if [[ $reply = 'quit' ]]; then
         break
-    elif [[ $reply = $key ]]; then
+    elif [[ $reply = $file ]]; then
         printf 'Correct! 🎉\n\n'
     else
-        printf 'No, sorry, it was %s%s%s.\n\n' "$(tput bold)" "$key" "$(tput sgr0)"
+        printf 'No, sorry, it was %s%s%s.\n\n' "$(tput bold)" "$file" "$(tput sgr0)"
     fi
 done
